version: "3.9"

services:
  app:
    build: .
    container_name: favourite-assets
    ports:
      - "8080:8080"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: dev-mem
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-realm/realm-export.json:/opt/keycloak/data/import/realm-export.json
